/*node {
    try {
        docker.image("maven").inside {
            stage ("Clone code Git"){
                checkout scm
            }

            stage ("Check environment") {
                sh "mvn --version"
                sh "java --version"
                sh "javac --version"
            }

            stage ("Check path") {
                sh "cd /root/.jenkins/workspace/java-full-pipeline/demojenkins/ && ls"
            }

            stage ("Build") {
                sh "mvn -f /root/.jenkins/workspace/java-full-pipeline/demojenkins/ package"
            }

            stage ("Test") {
                sh "mvn -f /root/.jenkins/workspace/java-full-pipeline/demojenkins/ test"
            }
            
            stage ("Display report") {
                echo "Display report ...."
            }

            stage ("Deloy") {
                echo "Deloy ...."
            }
        }
    } catch (e) {
        throw e
    } finally {
        def currentResult = currentBuild.result ?: 'SUCCESS'

        def DATE = sh(returnStdout: true, script: "date +'%d-%m-%y'")

        def NOTIFICATION_SUCCESS = "'{\"text\":\"NAM == SUCCESS, ${DATE}\"}'"
        def NOTIFICATION_FAILTURE = "'{\"text\":\"NAM == FAILTURE ${DATE}\"}'"
        def API_A = "https://hooks.slack.com/services/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"
        

        if (currentResult == 'SUCCESS') {
            sh "curl -X POST -H 'Content-type: application/json' --data ${NOTIFICATION_SUCCESS} ${API_A}"
        } else {
            sh "curl -X POST -H 'Content-type: application/json' --data ${NOTIFICATION_FAILTURE} ${API_A}"
        }
    }
}*/

pipeline {
    agent any

    environment {
        COMMAND = "curl -X POST -H 'Content-type: application/json' --data"

        API_A = 'https://hooks.slack.com/services/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'
        
        DATE = sh(returnStdout: true, script: "date +'%d-%m-%y'")

        NOTIFICATION_SUCCESS = "'{\"text\":\"NAM == SUCCESS, ${DATE}\"}'"
        NOTIFICATION_FAILTURE = "'{\"text\":\"NAM == FAILTURE, ${DATE}\"}'"        
    }

    stages {
        stage ("Begin") {
            steps {
                sh "apt install maven"
            }
        }

        stage ("Build") {
            steps {
                sh 'mvn -f demojenkins/pom.xml clean package'
            }
        }

        stage ("Test") {
            steps {
                step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])
            }
        }

        stage ("Deloy") {
            steps {
                //sh "java -jar /root/.jenkins/workspace/java-full-pipeline/demojenkins/target/demojenkins-0.0.1-SNAPSHOT.jar"

                echo 'Deloy ....'
            }
        }
    }

    post {
        success {
            sh "${COMMAND} ${NOTIFICATION_SUCCESS} ${API_A}"
        }

        failure {
            sh "${COMMAND} ${NOTIFICATION_FAILTURE} ${API_A}"
        }
    }
}




// stage deloy QA
// - copy file jar to VM 2 
// - excute command as jenkins file 
// note: Tao con VM 2, deloy len con VM 2
